name: Packaging workflow

# Manually triggered for now
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'build tags'
        required: false

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: true
          install: git

      - name: "Build package"
        shell: msys2 {0}
        run: |
          echo "Current dir" && pwd && ls -l
          echo "Dev" && ls -l dev/win_installer
          cd dev/win_installer
          ./build.sh
          echo "End of build" && ls -l

      - name: "Upload binaries"
        uses: actions/upload-artifact@v2
        with:
          path: dev/win_installer/advene-*-installer.exe
