name: Packaging workflow

# Manually triggered for now
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'build tags'
        required: true

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          path: /advene
          fetch-depth: 0

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: true
          install: git

      - name: "Build package"
        shell: msys2 {0}
        run: |
          cd /advene/dev/win_installer
          ./build.sh
          ls -l /advene/dev/win_installer

      - name: "Upload binaries"
        uses: actions/upload-artifact@v2
        with:
          path: /advene/dev/win_installer/advene-*-installer.exe
